# Generated by Django 5.1.7 on 2025-03-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='isActice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(unique=True)),
                ('databasesparams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.databasesparams')),
            ],
        ),
    ]
